### ISSUE TITLE
Getting connection to vesync failed which is causing homebridge to stop and restart constantly

### ISSUE THREAD

**Issue by dakovacic** [mickgiles/homebridge-vesync#20]
Starting yesterday 9/6/2024 19:40:04 EDT, I started seeing **[VesyncPlug] Connecting to Vesync failed!** in mt logs.

That continued periodically until I attempted to access a Vesync device about 7:30 this morning at which point I started seeing:

[07/09/2024, 07:33:17] [VesyncPlug] Connecting to Vesync failed!
[07/09/2024, 07:33:17] TypeError: Cannot read properties of null (reading 'find')
    at /var/lib/homebridge/node_modules/homebridge-vesync-v2/index.js:223:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[07/09/2024, 07:33:17] Got SIGTERM, shutting down Homebridge...

After which point, I am just seeing homebridge shut down and restart constantly with 

[07/09/2024, 07:34:23] [homebridge-vesync-v2] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[07/09/2024, 07:34:23] [homebridge-vesync-v2] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[07/09/2024, 07:34:23] [homebridge-vesync-v2] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[07/09/2024, 07:34:23] [homebridge-vesync-v2] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[07/09/2024, 07:34:23] [homebridge-vesync-v2] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.

[07/09/2024, 07:36:14] [VesyncPlug] Connecting to Vesync failed!
[07/09/2024, 07:36:14] [VesyncPlug] Connecting to Vesync failed!
[07/09/2024, 07:36:14] TypeError: Cannot read properties of null (reading 'find')
    at /var/lib/homebridge/node_modules/homebridge-vesync-v2/index.js:223:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[07/09/2024, 07:36:14] [VesyncPlug] Connecting to Vesync failed!
[07/09/2024, 07:36:14] TypeError: Cannot read properties of null (reading 'find')
    at /var/lib/homebridge/node_modules/homebridge-vesync-v2/index.js:223:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[07/09/2024, 07:36:14] [VesyncPlug] Connecting to Vesync failed!
[07/09/2024, 07:36:14] TypeError: Cannot read properties of null (reading 'find')
    at /var/lib/homebridge/node_modules/homebridge-vesync-v2/index.js:223:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[07/09/2024, 07:36:14] [VesyncPlug] Connecting to Vesync failed!
[07/09/2024, 07:36:14] TypeError: Cannot read properties of null (reading 'find')
    at /var/lib/homebridge/node_modules/homebridge-vesync-v2/index.js:223:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[07/09/2024, 07:36:14] Got SIGTERM, shutting down Homebridge...
[07/09/2024, 07:36:15] [Living Room] INFO - shutdown
[07/09/2024, 07:36:15] [VesyncPlug] Connecting to Vesync failed!
[07/09/2024, 07:36:15] TypeError: Cannot read properties of null (reading 'find')
    at /var/lib/homebridge/node_modules/homebridge-vesync-v2/index.js:223:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Followed by Homebridge again shutting down and a repetition of the whole sequence. I finally had to disable the Vesync plugin to stabilize homebridge and let it come fully up.

There were no changes to Homebridge prior to the plugin failing to connect and the Vesync app on mt iPhone still connects normally using the same user ID and password configured into the plugin.

The last time this occurred (in June) it was caused by a change in the Vesync API.

**Comment by mickgiles** [comment]
That error occurs when the API returns no devices. The only way I can see you getting this error is if your username/password is incorrect or something like a firewall is blocking homebridge from connecting to the API.
Additionally, I would suggest you put this and other plugins in their own child bridge. That will prevent the plugins from crashing homebridge when something goes wrong, it will just restart the child bridge not affecting the rest of the plugins.

**Comment by dakovacic** [comment]
Very odd - today when I reenabled the plugin it connected to Vesync found all my devices and everything came up just fine - don’t know what could eb causing that - didn’t make any changes to the user ID and password I am using so I don’t know…
