### ISSUE TITLE
Add Levoit smart tower fan support

### ISSUE THREAD

**Issue by vincentjr** [mickgiles/homebridge-vesync#23]
Out of all the Levoit Homebridge plugins, none of them seem to support any of the tower fans that appear in the VeSync app. For example - https://levoit.com/products/42-tower-fan

**Comment by mickgiles** [comment]
I added support however don't own the device to test so please do let me know if this works or not.

**Comment by vincentjr** [comment]
Ah didn't notice the logs. I'm seeing:

```
[08/12/2024, 21:47:36] [VesyncPlug] Adding device:  vsaqeeda4d94 Gym fan
[08/12/2024, 21:47:36] [VesyncPlug] ERROR: TypeError: Cannot read properties of undefined (reading 'getService')
```

**Comment by mickgiles** [comment]
I made some additional updates. can you try again

**Comment by vincentjr** [comment]
Thanks! I saw a couple changes to the purifiers in my accessories. This popped up in the logs:

```
[08/12/2024, 22:09:59] [VesyncPlug] Adding device:  vsaq46c0aab8 Air Purifier LR
[Air Purifier LR@Air Purifier LR@On] Characteristic not in required or optional characteristic section for service AirPurifier. Adding anyway.
[08/12/2024, 22:09:59] [VesyncPlug] ERROR: TypeError: Cannot read properties of undefined (reading 'getService'
```

I believe the fan is in the accessories list but toggling the switch isn't doing anything and I'm not seeing anything in the logs. I'm going to try upgrading to the latest node (although this plugin is looking for ~20 it looks like)

**Comment by vincentjr** [comment]
No luck. All the devices (3 purifiers and 1 fan) are all throwing the following message every couple seconds:

```
[08/12/2024, 22:31:03] [VesyncPlug] ERROR: TypeError: Cannot read properties of undefined (reading 'getService')
```

**Comment by mickgiles** [comment]
can you give it another try

**Comment by vincentjr** [comment]
Hmm it was erroring. So I completely removed and attempted to reinstall.

```
USER: homebridge
DIR: /var/lib/homebridge
CMD: npm install --save homebridge-vesync-v2@2.5.9

npm error code ETARGET
npm error notarget No matching version found for homebridge-vesync-v2@2.5.9.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
npm error A complete log of this run can be found in: /home/homebridge/.npm/_logs/2024-12-09T04_00_33_096Z-debug-0.log

Error: Operation failed with code 1.
You can download this log file for future reference.
See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.
```

**Comment by vincentjr** [comment]
```
22 verbose type version
23 verbose stack homebridge-vesync-v2: No matching version found for homebridge-vesync-v2@2.5.9.
23 verbose stack     at module.exports (/opt/homebridge/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:215:23)
23 verbose stack     at RegistryFetcher.manifest (/opt/homebridge/lib/node_modules/npm/node_modules/pacote/lib/registry.js:130:54)
23 verbose stack     at async #fetchManifest (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1202:20)
23 verbose stack     at async #nodeFromEdge (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1040:19)
23 verbose stack     at async #buildDepStep (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:904:11)
23 verbose stack     at async Arborist.buildIdealTree (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:181:7)
23 verbose stack     at async Promise.all (index 1)
23 verbose stack     at async Arborist.reify (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
23 verbose stack     at async Install.exec (/opt/homebridge/lib/node_modules/npm/lib/commands/install.js:150:5)
23 verbose stack     at async Npm.exec (/opt/homebridge/lib/node_modules/npm/lib/npm.js:207:9)
24 error code ETARGET
25 error notarget No matching version found for homebridge-vesync-v2@2.5.9.
26 error notarget In most cases you or one of your dependencies are requesting
26 error notarget a package version that doesn't exist.
27 silly unfinished npm timer reify 1733716835523
28 silly unfinished npm timer reify:loadTrees 1733716835525
```

**Comment by vincentjr** [comment]
I believe the Homebridge UI is defaulting the `latest` to version 2.5.9 but your latest git package is 2.5.5. So I manually pointed to 2.5.5, not sure where Homebridge UI is reading the 2.5.9 from.

Loading it up now

**Comment by mickgiles** [comment]
I think that is just an npm caching issue, try again, and maybe a couple of times, and it will download. 
the latest version as of now is 2.5.10

**Comment by vincentjr** [comment]
Loaded 2.5.10, no dice. Is there another way to help debug for you that would be useful?

```
[08/12/2024, 23:10:45] [VesyncPlug] Adding device:  vsaqf5063294e2 Air Purifier 
[08/12/2024, 23:10:45] [VesyncPlug] ERROR: TypeError: Cannot read properties of undefined (reading 'getService')
[08/12/2024, 23:11:45] [VesyncPlug] Adding device:  vsaqf5063294e2 Air Purifier 
[08/12/2024, 23:11:45] [VesyncPlug] ERROR: TypeError: Cannot read properties of undefined (reading 'getService')
[08/12/2024, 23:12:45] [VesyncPlug] Adding device:  vsaqf5063294e2 Air Purifier 
[08/12/2024, 23:12:45] [VesyncPlug] ERROR: TypeError: Cannot read properties of undefined (reading 'getService')
```

**Comment by mickgiles** [comment]
I've taken another crack at it. I think I found the proper APIs for those devices if you want to try again

**Comment by vincentjr** [comment]
```
[10/12/2024, 09:48:25] ====================
[10/12/2024, 09:48:25] ERROR LOADING PLUGIN homebridge-vesync-v2:
[10/12/2024, 09:48:25] Error: Cannot find module './hrequest'
Require stack:
- /var/lib/homebridge/node_modules/homebridge-vesync-v2/lib/EtekCityClient.js
- /var/lib/homebridge/node_modules/homebridge-vesync-v2/lib/platform.js
- /var/lib/homebridge/node_modules/homebridge-vesync-v2/index.js
- /var/lib/homebridge/node_modules/homebridge/lib/plugin.js
- /var/lib/homebridge/node_modules/homebridge/lib/pluginManager.js
- /var/lib/homebridge/node_modules/homebridge/lib/api.js
- /var/lib/homebridge/node_modules/homebridge/lib/server.js
- /var/lib/homebridge/node_modules/homebridge/lib/cli.js
- /var/lib/homebridge/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1249:15)
    at Function.Module._load (node:internal/modules/cjs/loader:1075:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:138:16)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-vesync-v2/lib/EtekCityClient.js:3:22)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1708:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    ```

**Comment by mickgiles** [comment]
can you try again

**Comment by vincentjr** [comment]
Looking a little better now but still throwing errors:

```
[Gym fan@Gym fan@Swing Mode] Characteristic not in required or optional characteristic section for service Fan. Adding anyway.
[10/12/2024, 10:12:09] [VesyncPlug] ERROR: TypeError: Cannot read properties of undefined (reading 'getService')
[10/12/2024, 10:12:10] [VesyncPlug] Error getting rotation speed: TypeError: Cannot read properties of undefined (reading 'manualSpeedLevel')
    at FanDevice.getRotationSpeed (/var/lib/homebridge/node_modules/homebridge-vesync-v2/lib/devices/FanDevice.js:60:39)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[10/12/2024, 10:12:10] [VesyncPlug] Error getting swing mode: TypeError: Cannot read properties of undefined (reading 'oscillationSwitch')
    at FanDevice.getSwingMode (/var/lib/homebridge/node_modules/homebridge-vesync-v2/lib/devices/FanDevice.js:92:40)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[10/12/2024, 10:12:10] [VesyncPlug] Error getting power state: TypeError: Cannot read properties of undefined (reading 'powerSwitch')
    at FanDevice.getPowerState (/var/lib/homebridge/node_modules/homebridge-vesync-v2/lib/devices/FanDevice.js:32:40)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[10/12/2024, 10:12:10] [VesyncPlug] Error getting rotation speed: TypeError: Cannot read properties of undefined (reading 'manualSpeedLevel')
    at FanDevice.getRotationSpeed (/var/lib/homebridge/node_modules/homebridge-vesync-v2/lib/devices/FanDevice.js:60:39)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[10/12/2024, 10:12:10] [VesyncPlug] Error getting power state: TypeError: Cannot read properties of undefined (reading 'powerSwitch')
    at FanDevice.getPowerState (/var/lib/homebridge/node_modules/homebridge-vesync-v2/lib/devices/FanDevice.js:32:40)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[10/12/2024, 10:12:10] [VesyncPlug] Error getting swing mode: TypeError: Cannot read properties of undefined (reading 'oscillationSwitch')
    at FanDevice.getSwingMode (/var/lib/homebridge/node_modules/homebridge-vesync-v2/lib/devices/FanDevice.js:92:40)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    ```

**Comment by vincentjr** [comment]
```
[10/12/2024, 13:42:43] [VesyncPlug] Error getting swing mode: Error: Invalid response from device
    at FanDevice._getStatus (/var/lib/homebridge/node_modules/homebridge-vesync-v2/lib/devices/FanDevice.js:49:19)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at FanDevice.getSwingMode (/var/lib/homebridge/node_modules/homebridge-vesync-v2/lib/devices/FanDevice.js:125:28)
    ```

**Comment by vincentjr** [comment]
```
[10/12/2024, 16:04:41] [VesyncPlug] Connecting to Vesync failed!
[10/12/2024, 16:05:41] [VesyncPlug] {"traceId":"0.21835664053480786","code":-16906086,"msg":"Current user's daily request quota has been used up. The quota formula is \"3200 + 1500 * user owned device number\". Please note that we may change the constant in the formula","module":null,"stacktrace":null,"result":null}
```

I'll have to disable for now

**Comment by mickgiles** [comment]
yep me too. I've reverted to a safe version until I can test this more thoroughly

**Comment by vincentjr** [comment]
I got this running locally to help with debug. Poking around a little bit, my tower model should is `LTF-F422S-WUS` which is slightly different than the 2 listed. 

New to homebridge local dev so I'm not sure if that fully resolved it but the `getService` errors are not popping up in the logs when I add it

**Comment by mickgiles** [comment]
What I am working with is the APIs that another user posted here https://github.com/webdjoe/pyvesync/issues/242 in combination with a Levoit air purifier that I own to test all the characteristics. 
If you have the ability to verify that pyvesync works on your unit then at least I can trust the APIs will work once I sort out the characteristics and other core functionality of a fan type of device.

**Comment by vincentjr** [comment]
From pyvesync here is the Tower Fan Device payload:

```
{
  "timeZone": "TIME_ZONE",
  "acceptLanguage": "en",
  "accountID": "##_REDACTED_##",
  "token": "##_REDACTED_##",
  "appVersion": "2.8.6",
  "phoneBrand": "SM N9005",
  "phoneOS": "Android",
  "traceId": "1733945603",
  "method": "bypassV2",
  "debugMode": false,
  "deviceRegion": "US",
  "cid": "##_REDACTED_##",
  "deviceId": "vsaqeeda4d94b7ba7ec1143ed8c6f7f5",
  "configModule": "VS_WFON_STF_LTF-F422S-WUS_US",
  "configModel": "VS_WFON_STF_LTF-F422S-WUS_US",
  "payload": {
    "method": "getTowerFanStatus",
    "source": "APP",
    "data": {}
  }
}
```

Running:
```
my_fan = manager.fans[0]
my_fan.turn_on()
```

API request
```
2024-12-11 14:36:40,976 - DEBUG - =======call_api=============================
2024-12-11 14:36:40,976 - DEBUG - [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2024-12-11 14:36:40,976 - DEBUG - API call URL:
  https://smartapi.vesync.com/cloud/v2/deviceManaged/bypassV2
2024-12-11 14:36:40,976 - DEBUG - API call headers:
  {
  "Content-Type": "application/json; charset=UTF-8",
  "User-Agent": "okhttp/3.12.1"
}
2024-12-11 14:36:40,976 - DEBUG - API call json:
  {
  "timeZone": "TIME_ZONE",
  "acceptLanguage": "en",
  "accountID": "##_REDACTED_##",
  "token": "##_REDACTED_##",
  "appVersion": "2.8.6",
  "phoneBrand": "SM N9005",
  "phoneOS": "Android",
  "traceId": "1733945800",
  "method": "bypassV2",
  "debugMode": false,
  "deviceRegion": "US",
  "cid": "##_REDACTED_##",
  "deviceId": "vsaqeeda4d94b7ba7ec1143ed8c6f7f5",
  "configModule": "VS_WFON_STF_LTF-F422S-WUS_US",
  "configModel": "VS_WFON_STF_LTF-F422S-WUS_US",
  "payload": {
    "method": "setSwitch",
    "source": "APP",
    "data": {
      "powerSwitch": 1,
      "switchIdx": 0
    }
  }
}
```

Does turn on the fan!

**Comment by mickgiles** [comment]
this is very helpful, thanks! I'm still over my quota so once I'm unlocked I can hopefully get it working.

**Comment by vincentjr** [comment]
not great but some progress heh - https://github.com/mickgiles/homebridge-vesync/pull/24

**Comment by vincentjr** [comment]
or could probably rip what they're doing here - https://github.com/webdjoe/pyvesync/blob/master/src/pyvesync/helpers.py

**Comment by vincentjr** [comment]
I wound up setting up a server running pyvesync and then wrote a homebridge plugin that proxies the calls to that pyvesync server to get the fan support :x

**Comment by mickgiles** [comment]
> I wound up setting up a server running pyvesync and then wrote a homebridge plugin that proxies the calls to that pyvesync server to get the fan support :x

this is actually really clever

**Comment by mickgiles** [comment]
I have created a new project with more device coverage and will be easier to support moving forward. This project will be archived. Please see https://github.com/mickgiles/homebridge-tsvesync for the new plugin and to report any issues.
